version: '2'
services:
  hass:
    image: homeassistant/raspberrypi3-homeassistant
    container_name: hass
    hostname: hass
    ports:
      - 8123:8123
    volumes:
      - /home/pi/hass:/config
    environment:
      - TZ=Europe/Amsterdam
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host