version: '2'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    hostname: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /home/pi/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /home/pi/mosquitto/data:/mosquitto/data
      - /home/pi/mosquitto/log:/mosquitto/log
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
