version: '2'
services:
  rflinkgateway:
    container_name: rflinkgateway
    image: rflinkgateway:armv7
    hostname: rflinkgateway
    # ports:
    #   - 1883:1883
    #   - 9001:9001
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /home/pi/rflinkgateway/log:/var/log
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
