version: '2'
services:
  rflinkgateway:
    container_name: rflinkgateway
    image: arm32v7/python:3
    hostname: rflinkgateway
    # ports:
    #   - 1883:1883
    #   - 9001:9001
    volumes:
      - /home/pi/rflinkgateway/log:/var/log
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
