version: '2'

services:
  nzbget:
    image: lsioarmhf/nzbget:latest
    container_name: nzbget
    hostname: nzbget
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_nzbget:/config
      - /home/pi/downloads:/downloads
    restart: always
    ports:
      - 6789:6789
    networks:
      - backend

  sonarr:
    image: lsioarmhf/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    links:
      - nzbget
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/config_sonarr:/config
      - /home/pi/series:/tv
      - /home/pi/downloads:/downloads
    restart: always
    ports:
      - 8989:8989
    networks:
      - backend

  radarr:
    image: lsioarmhf/radarr:latest
    container_name: radarr
    hostname: radarr
    environment:
      - TZ=Europe/Amsterdam
    links:
      - nzbget
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/config_radarr:/config
      - /home/pi/movies:/movies
      - /home/pi/downloads:/downloads
    restart: always
    ports:
      - 7878:7878
    networks:
      - backend

networks:
  backend:
    driver: bridge
