version: '2'
services:
  db-dsmr:
    image: postgres
    container_name: db-dsmr
    volumes:
      - ~/dsmr/db:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader
    networks:
      - net-dsmr
  dsmr:
    container_name: dsmr
    image: ualex73/dsmr-reader-docker
    container_name: dsmr
    restart: unless-stopped
    volumes:
      - ~/dsmr/backups:/home/dsmr/app/backups
      - ~/dsmr/dev:/dev
    environment:
      - DB_HOST=db-dsmr
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
    ports:
      - 8888:80
    networks:
      - net-dsmr
networks:
  net-dsmr:
    driver: bridge