version: '2'

services:
  portainer:
    image: portainer/portainer:arm
    container_name: portainer
    hostname: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  domoticz:
    image: joshuacox/mkdomoticz:arm
    container_name: domoticz
    hostname: domoticz
    ports:
      - 8080:8080
    volumes:
      - /home/pi/config_domoticz:/config
    privileged: true
    restart: always
