version: '2'

services:
  domoticz:
    image: joshuacox/mkdomoticz:arm
    container_name: domoticz
    hostname: domoticz
    environment:
      TZ: "Europe/Amsterdam"
    ports:
      - 8181:8080
    volumes:
      - /home/pi/config_domoticz:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    restart: always