version: '2'

services:
  domoticz:
    image: cgatay/domoticz:4.10414-beta-arm
    container_name: domoticz
    hostname: domoticz
    environment:
      TZ: "Europe/Amsterdam"
    ports:
      - 8181:8080
    volumes:
      - /home/pi/config_domoticz:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    privileged: true 
    restart: always